CREATE DATABASE SAF_3T;
GO

USE SAF_3T;
GO

CREATE TABLE TipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeTipoUsuario VARCHAR (18) UNIQUE NOT NULL
);
GO 

CREATE TABLE TipoCarroceria(
	IdTipoCarroceria INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeTipoCarroceria VARCHAR (30) UNIQUE NOT NULL
);
GO

CREATE TABLE TipoVeiculo(
	IdTipoVeiculo INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeTipoVeiculo VARCHAR (20) UNIQUE NOT NULL
);
GO

CREATE TABLE TipoErro(
	IdTipoErro INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeTipoErro VARCHAR (30) UNIQUE NOT NULL
);
GO

CREATE TABLE TipoCarga(
	IdTipoCarga INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeTipoCarga VARCHAR (20) UNIQUE NOT NULL
);
GO

CREATE TABLE TipoCheckList(
	IdTipoCheckList INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeTipoCheckList VARCHAR (15) UNIQUE NOT NULL
);
GO

CREATE TABLE Marca(
	IdMarca TINYINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NomeMarca VARCHAR (20) NOT NULL
);
GO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	Nome VARCHAR (12) NOT NULL,
	Sobrenome VARCHAR (25) NOT NULL,
	DDD VARCHAR (3) NOT NULL,
	Telefone VARCHAR (10) NOT NULL,
	CPF CHAR (11) UNIQUE NOT NULL,
);
GO

CREATE TABLE Carroceria(
	IdCarroceria INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IdTipoCarga INT FOREIGN KEY REFERENCES TipoCarga(IdTipoCarga) NOT NULL,
	IdTipoCarroceria INT FOREIGN KEY REFERENCES TipoCarroceria(IdTipoCarroceria) NOT NULL,
	Cubagem VARCHAR (30) NOT NULL,
	Peso VARCHAR (30) NOT NULL,
);
GO

CREATE TABLE Veiculo(
	IdVeiculo INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdMarca TINYINT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	IdTipoVeiculo INT FOREIGN KEY REFERENCES TipoVeiculo(IdTipoVeiculo) NOT NULL,
	IdCarroceria INT FOREIGN KEY REFERENCES Carroceria(IdCarroceria) NOT NULL,
	Placa CHAR(8) UNIQUE NOT NULL,
	DataAquisicao DATETIME NOT NULL
);
GO

CREATE TABLE CheckList(
	IdCheckList INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IdTipoCheckList INT FOREIGN KEY REFERENCES TipoCheckList(IdTipoCheckList) NOT NULL,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	DataCheckList DATETIME NOT NULL
);
GO

CREATE TABLE TabelaErro(
	IdErro INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IdTipoErro INT FOREIGN KEY REFERENCES TipoErro(IdTipoErro),
	IdCheckList INT FOREIGN KEY REFERENCES CheckList(IdCheckList),
	DescricaoErro VARCHAR (250),
	ImagemErro VARCHAR (255)
);
GO

CREATE TABLE TabelaCorrecao(
	IdCorrecao INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IdTipoErro INT FOREIGN KEY REFERENCES TipoErro(IdTipoErro) NOT NULL,
	IdCheckList INT FOREIGN KEY REFERENCES CheckList(IdCheckList) NOT NULL,
	DescricaoCorrecao VARCHAR (250),
	ImagemCorrecao VARCHAR (255),
);
GO